/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Storage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebSocketAPI": {
      "managementEndpoint": string
      "type": "sst.aws.ApiGatewayWebSocket"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}